import os

MINING_DIFFICULTY = os.getenv('MINING_DIFFICULTY', None)
NUMBER_OF_NODES = os.getenv('NUMBER_OF_NODES', None)
BLOCK_CAPACITY = os.getenv('BLOCK_CAPACITY', None)
BOOTSTRAP_IP = '127.0.0.1'
BOOTSTRAP_PORT = '5000'
LOCAL = True